---
#/etc/ansible/roles/zooinstall/tasks/main.yml
# tasks file for zooinstall
   - name: Zookeeper Installation
     debug:
       msg: "Zookeeper Installation"

   - name: Check if Zookeeper already installed | Exit Play if zookeeper already exists
     stat:
       path: /opt/zookeeper/conf/zoo.cfg
     register: stat_result
     ignore_errors: yes

   - name: Exit Play if Zookeeper already exists
     meta: end_play
     when: stat_result.stat.exists == True

   - name: Install all packages
     yum: name={{item}} state=present update_cache=yes
     with_items:
       - java-1.8.0-openjdk.x86_64
       - firewalld
       - wget
  
   - name: Extract zookeeper-3.4.10.tar.gz into /opt
     unarchive:
       src: ./../files/zookeeper-3.4.10.tar.gz
       dest: /opt

   - copy:
       src: ./../files/zooinstall.sh
       dest: /home/zooinstall.sh

   - name: setting permission
     file: dest=/home/zooinstall.sh mode=a+x

   - name: executing the script on remote machine
     shell: sh /home/zooinstall.sh {{ ip1 }} {{ ip2 }} {{ ip3 }} {{ id1 }} {{ id2 }} {{ id3 }}
